spring:
  application.name: hello-world
  cloud.kubernetes.reload.enabled: true
server.port: 8100
management:
  endpoint:
    restart:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true